---
title: "ISD Financial Analysis"
subtitle: "`r paste(district_name, district_code) `"
---




```{r setup, include=FALSE}
knitr::opts_chunk$set(dev = "png", 
                      # dev.args = list(type = "cairo-png"), # anti-aliasing 
                      echo = FALSE, 
                      quiet = TRUE,
                      warning = FALSE, 
                      message = FALSE,
                      cache = FALSE,
                      fig.width= 7,
                      fig.height= 4,
                      dev = 'svg',
                      # out.width = "200%",
                      # out.height = "200%",
                      fig.align='center',
                      root.dir = TannersTools::tt_dir_projects())


flextable::set_flextable_defaults(fonts_ignore=TRUE)


```


```{r, echo = FALSE}

sass::sass(sass::sass_file(TannersTools::tt_dir_projects("financial.analysis", "assets", "FA_Style.scss")))



```



```{r}

element_table_isd_rev_exp_bal <- function(fund, title) {
  
  data <- 
    FA_Data_ISD %>% 
  filter(fund == {{ fund }}) %>% 
  select(FY, rev, transfer.in, exp, transfer.out, bal, bal.pct.rev, bal.pct.exp)
  
  if(nrow(data) != 0){
    
     data %>% 
      flextable() %>% 
      set_header_labels(FY = "Fiscal Year",
                        rev = "Revenue",
                        transfer.in = "Transfer In",
                        exp = "Expenditure",
                        transfer.out = "Transfer Out",
                        bal = "Fund Balance Amount",
                        bal.pct.rev = "Fund Balance % of Revenue",
                        bal.pct.exp = "Fund Balance % of Expenditure") %>% 
      colformat_num(j = "FY",
                    big.mark = "") %>%
      colformat_double(j = c("bal.pct.rev", 
                             "bal.pct.exp"), 
                       suffix = "%") %>% 
      flextable_custom_theme(title = {{ title }})
    
  }
 
  
}



```


```{r}


element_fig_isd_rev_exp <- function(fund, transfers) {
  
  data <- 
    FA_Data_ISD %>% 
    filter(fund == {{ fund }}) %>% 
    select(FY, rev, exp) %>% 
    pivot_longer(cols = c(rev, exp)) %>% 
    filter(!is.na(value)) %>%
    filter(FY != fiscal.year) %>% 
      mutate(name = case_when(name == "rev"  ~ "Revenue",
                              name == "exp" ~ "Expenditure"))
  
  if(nrow(data) != 0){
    
  data %>% 
    ggplot(aes(x = FY, y = value, 
             group = name,  color = name, linetype = name))+
    geom_line(size = line_size) +
  scale_x_continuous(breaks = seq(1990, fiscal.year-1, by = 1) )+
    scale_y_continuous(labels = number_format(big.mark = ",")) +
    labs(title = "<span style='color: #00A651'> Revenue</span> and <span style='color: #C2002F'>Expenditure</span>",
         subtitle = "Excluding Transfers",
         x = "Fiscal Year",
         y = "")+
    scale_color_manual(values = c(mea_red, mea_green)) +
    scale_fill_manual(values = c(mea_red, mea_green)) +
    scale_linetype_manual(values=c("twodash", "solid"))+
    theme(legend.box.background = element_rect(color= mea_gray, size=1),
          legend.title = element_blank(),
          legend.position = "bottom",
          plot.title = element_markdown())

    
  }
  
}



```

```{r}

element_fig_isd_rev_exp_with_transfers <- function(fund, transfers) {
  
  data <- 
    FA_Data_ISD %>% 
    filter(fund == {{ fund }}) %>% 
    mutate(rev = rev + transfer.in,
           exp = exp + transfer.out) %>% 
    select(FY, rev, exp) %>% 
    pivot_longer(cols = c(rev, exp)) %>% 
    filter(!is.na(value)) %>%
    filter(FY != fiscal.year) %>% 
    mutate(name = case_when(name == "rev"  ~ "Revenue",
                              name == "exp" ~ "Expenditure"))
  
  
  if(nrow(data) != 0){
    data %>% 
    ggplot(aes(x = FY, y = value, 
             group = name,  color = name, linetype = name))+
    geom_line(size = line_size) +
      scale_x_continuous(breaks = seq(1990, fiscal.year-1, by = 1) )+
    scale_y_continuous(labels = number_format(big.mark = ",")) +
    labs(title = "<span style='color: #00A651'> Revenue</span> and <span style='color: #C2002F'>Expenditure</span>",
         subtitle = "Including Transfers",
         x = "Fiscal Year",
         y = "")+
    scale_color_manual(values = c(mea_red, mea_green)) +
    scale_fill_manual(values = c(mea_red, mea_green)) +
    scale_linetype_manual(values=c("twodash", "solid"))+
    theme(legend.box.background = element_rect(color= mea_gray, size=1),
          legend.title = element_blank(),
          legend.position = "bottom",
          plot.title = element_markdown())
  
  }
  
}



```



```{r}

element_fig_isd_fund_balance <- function(fund) {
  
  data <- 
    FA_Data_ISD %>% 
  filter(fund == {{ fund }}) %>% 
  select(FY, bal.pct.rev) %>% 
  filter(FY != fiscal.year) %>% 
  mutate(bal.pct.exp = bal.pct.rev / 100)
  
    
  if(nrow(data) != 0){
    
    data %>% 
    ggplot(aes(x = FY, y = bal.pct.exp)) +
  geom_line(size = line_size)+
  scale_x_continuous(breaks = seq(1990, fiscal.year-1, by = 1) )+
  scale_y_continuous(labels = percent_format()) +
  labs(title = "Fund Balance as % of Revenue",
       x = "Fiscal Year",
       y = "")+
  theme(legend.box.background = element_rect(color= mea_gray, size=1),
        legend.title = element_blank(),
        legend.position = "bottom",
        plot.title = element_markdown())
    
    
  }  
  
  
  
  
}
  
 
  

```





## General Education Fund

```{r}
element_table_isd_rev_exp_bal(fund = 11, title = "General Fund")
element_fig_isd_rev_exp(fund = 11)
element_fig_isd_rev_exp_with_transfers(fund = 11)
element_fig_isd_fund_balance(fund = 11)

```



## Special Education Fund

```{r}

element_table_isd_rev_exp_bal(fund = 22, title = "Special Education Fund")
element_fig_isd_rev_exp(fund = 22)
element_fig_isd_rev_exp_with_transfers(fund = 22)
element_fig_isd_fund_balance(fund = 22)

```

```{r}

 


show_voced_header <- 
  FA_Data_ISD %>% 
  filter(fund == 26) %>%
  nrow() > 0
  

```



```{asis, echo = show_voced_header}

## Vocational Education Fund

```

```{r}

element_table_isd_rev_exp_bal(fund = 26, title = "Vocational Education Fund")
element_fig_isd_rev_exp(fund = 26)
element_fig_isd_rev_exp_with_transfers(fund = 26)
element_fig_isd_fund_balance(fund = 26)

```



## Transfers

```{r}

Transfer_Data_ISD %>% 
  select(transfer.from.fund.name, transfer.to.fund.name, amount) %>%
  flextable() %>% 
  set_header_labels(transfer.from.fund.name = "From", 
                    transfer.to.fund.name = "To",
                    amount = "Amount") %>% 
   colformat_double(j = "amount", 
                    big.mark = ",", digits = 0) %>%
  flextable_custom_theme(title = "Transfers")


```


## Taxable Value



```{r}


FA_Data_ISD %>% 
  filter(fund == 11) %>% 
  arrange(FY) %>% 
  mutate(sev = sev/ 1000,
         sev.chg = sev - lag(sev),
         sev.pct.chg = (sev.chg / lag(sev)) * 100) %>% 
  select(FY, sev, sev.chg, sev.pct.chg) %>% 
  flextable() %>% 
  set_header_labels(FY = "Fiscal Year",
                    sev = "Taxable Value (Thousands)",
                    sev.chg = "Change",
                    sev.pct.chg = "% Change"
                    ) %>% 
  colformat_num(j = "FY", big.mark = "") %>%
  colformat_double(j = c("sev", "sev.chg"), big.mark = ",", digits = 0)%>%
  colformat_double(j = "sev.pct.chg", suffix = "%") %>% 

  flextable_custom_theme(title = "Taxable Value")




```

```{r}

FA_Data_ISD %>% 
  filter(fund == 11) %>% 
  ggplot(aes(x = FY, y = sev / 1000)) +
  geom_area(color = mea_gray, fill = mea_gray_light, size = line_size) +
  scale_x_continuous(breaks = seq(1990, 2100, by = 1) )+
  scale_y_continuous(labels = number_format(big.mark = ",", prefix = "$")) +
  labs(title = "Taxable Value",
       x = "Fiscal Year",
       y = "Thousands")



```

\newpage


```{r}


FA_Data_ISD %>% 
  filter(fund == 11) %>% 
  mutate(sev = sev / 1000,
         millage.rev.oper = sev * milloper,
         millage.rev.se = sev  * millspeced,
         millage.rev.voc = sev * millvoced,
         millage.rev.rem = sev * enhancemnt) %>% 
  select(FY, sev, millage.rev.oper, millage.rev.se, millage.rev.voc, millage.rev.rem) %>% 
  flextable() %>% 
  set_header_labels(FY = "Fiscal Year",
                    sev = "Taxable Value (Thousands)",
                    millage.rev.oper = "Operational Millage Revenue",
                    millage.rev.se = "Special Education Millage Revenue",
                    millage.rev.voc = "Vocational Education Millage Revenue",
                    millage.rev.rem = "Regional Enhancement Millage Revenue"
                    ) %>% 
  colformat_num(digits = 0) %>%
  colformat_num(j = "FY", digits = 0, big.mark = "") %>%

  flextable_custom_theme(title = "Millage Revenue")

  

FA_Data_ISD %>% 
  filter(fund == 11) %>% 
  select(FY, sev, milloper,  millspeced, millvoced, enhancemnt) %>% 
  flextable() %>% 
  set_header_labels(FY = "Fiscal Year",
                    sev = "Taxable Value (Thousands)",
                    milloper = "Operational Millage Rate",
                    millspeced = "Special Education Millage Rate",
                    millvoced = "Vocational Education Millage Rate",
                    enhancemnt = "Regional Enhancement Millage Rate"
                    ) %>% 
  colformat_double( digits = 4) %>%
  colformat_num(j = "sev", digits = 0) %>%
  colformat_num(j = "FY", digits = 0, big.mark = "") %>%
  flextable_custom_theme(title = "Millage Rates")

  
```



