---
output: html_document
---

## State Aid Membership

State aid membership is the blended enrollment count used by the state to determine funding. This metric is the sum of 90% from the October count and 10% from the previous school year's February count. "Membership" is defined in state law in [MCL 388.1606(4)](https://www.legislature.mi.gov/Laws/MCL?objectName=MCL-388-1606), and regulatory guidance is produced each year through MDE's annual [Pupil Accounting Manual](https://www.michigan.gov/mde/services/financial-management/state-aid/publications/pupil-accounting-manual-pam) (PAM).



```{r}

FA_Data_District %>%
  select(FY, cy.d.pupilcnt, cy.d.pupilcnt.chg, cy.d.pupilcnt.pct.chg) %>%
  flextable() %>%
  set_header_labels(FY = "Fiscal Year",
                    cy.d.pupilcnt = "State Aid Membership",
                    cy.d.pupilcnt.chg = "Change",
                    cy.d.pupilcnt.pct.chg = "Pct Change") %>%
  colformat_num(j = "FY", big.mark = "") %>%
  colformat_double(j = c("cy.d.pupilcnt", "cy.d.pupilcnt.chg"), big.mark = ",", )%>%
  colformat_double(j = "cy.d.pupilcnt.pct.chg", suffix = "%") %>% 
  bg(j = "cy.d.pupilcnt", bg = mea_blue_light, part = "all") %>%

  flextable_custom_theme()


```


```{r}

yaxis_min <- 0
yaxis_max <- max(FA_Data_District$cy.d.pupilcnt)* 1.15

FA_Data_District %>%
  ggplot(aes(x = FY))+
  geom_col(aes(y = cy.d.pupilcnt), fill = mea_blue, size = 0)+
  scale_x_continuous(breaks = seq(1990, 2100, by = 1) )+
  scale_y_continuous(labels = number_format(big.mark = ","),
                     limits = c(yaxis_min, yaxis_max))+
  labs(title = "State Aid Membership",
       x = "Fiscal Year",
       y = "")




```








