---

---

## Original Budget and Actual


```{r}
prior.years.to.show <- 9
```




```{r}


FA_Data_District %>%
  ungroup() %>% 
  filter(FY != fiscal.year) %>% 
  select(FY, db.orig.surplus.deficit, fid.surplus.deficit, db.orig.surplus.error) %>%
  flextable() %>%
  set_header_labels(FY = "Fiscal Year",
                    fid.surplus.deficit = "Actual Surplus/Deficit",
                    db.orig.surplus.deficit = "Original Budget Surplus/Deficit",
                    db.orig.surplus.error = "Original Budget Error (Budget - Actual)") %>%
  colformat_num(j = "FY",
                big.mark = "") %>%
  colformat_double(j = c("fid.surplus.deficit",
                         "db.orig.surplus.deficit"),
                   big.mark = ",",
                   digits = 0) %>%
  
  # Option #1. this code does a light shade for the two columns.
  bg(j = "fid.surplus.deficit", bg = "#d1e8fa", part = "all") %>%
  bg(j = "db.orig.surplus.deficit", bg = "#fad1db", part = "all") %>%
  
  
  # option #2. dark shade on the header. Decided to keep it the same
      # bg(j = "fid.surplus.deficit", bg = mea_blue, part = "header") %>%
      # color(j = "fid.surplus.deficit",
      #       color = "white", part = "header") %>%
      # 
      # bg(j = "db.orig.surplus.deficit", bg = mea_red, part = "header") %>%
      # color(j = "db.orig.surplus.deficit",
      #       color = "white", part = "header") %>%

  flextable_custom_theme()




```


```{r eval = FALSE}

# old version of figure no longer in use
FA_Data_District %>%
  ggplot(aes(x = FY)) +
  geom_col(aes(y = fid.surplus.deficit), 
           fill = mea_blue,
           width = .25,
           just = 0)+
  geom_col(aes(y = db.orig.surplus.deficit),
           fill = mea_red,
           width = .25,
           just = 1) +
  geom_hline(yintercept = 0)+
  scale_x_continuous(breaks = seq(1990, 2100, by = 1) )+
  scale_y_continuous(labels = number_format(big.mark = ",")) +
  labs(title = "<span style='color: #C2002F '> Original Budget</span> and <span style='color: #003057'> Actual</span> Surplus/Deficit",
       x = "Fiscal Year",
       y = "") +
  theme(
    plot.title = element_markdown()
  )

```


```{r }

FA_Data_District %>%
  filter(FY != fiscal.year,
        !is.na(fid.surplus.deficit) & !is.na(db.orig.surplus.deficit)) %>% 
  ggplot(aes(x = FY)) +
  geom_hline(yintercept = 0)+
  geom_segment(aes(xend = FY, y = fid.surplus.deficit, yend = db.orig.surplus.deficit)) +
  geom_point(aes(y = fid.surplus.deficit, 
                 color = "Actual",
                 shape = "Actual"), 
             size = 3, alpha = 1)+
  geom_point(aes(y = db.orig.surplus.deficit, 
                 color = "Original Budget",
                 shape = "Original Budget"),
           # color = mea_red, 
           size = 3, alpha = 1) +
  
  scale_x_continuous(breaks = seq(1990, 2100, by = 1) )+
  scale_y_continuous(labels = number_format(big.mark = ",")) +
  labs(title = "Surplus/Deficit",
       subtitle = "<span style='color: #C2002F '> Original Budget</span> vs. <span style='color: #003057'>Actual</span>",
       x = "Fiscal Year",
       y = "") +
  scale_color_manual(name = "", values = c("Original Budget" = mea_red, "Actual" = mea_blue))+
  scale_shape_manual(name = "", values = c("Original Budget" = "circle", "Actual" = "square")) +
  theme(
    plot.subtitle = element_markdown(),
    legend.box.background = element_rect(color= mea_gray, size=1),
        legend.position = "bottom"  )



```




\newpage



```{r}


FA_Data_District %>% 
  filter(FY > (fiscal.year - prior.years.to.show),
         !is.na(est.1.rev.total.pct.act)) %>% 
  select(FY, db.original.total.revenue, fid.r.total.audit, db.orig.rev.error
         # db.final.total.revenue, db.final.rev.error
         ) %>% 
  flextable() %>% 
  set_header_labels(
                  FY = "Fiscal Year",
                  fid.r.total.audit = "Actual Revenue",
                  db.original.total.revenue = "District Original Budgeted Revenue",
                  # db.final.total.revenue = "District Final Budgeted Revenue",
                  db.orig.rev.error = "Original Budget Error (Budget - Actual)"
                  # db.final.rev.error = "Final Budget Error (Budget - Actual)"
                  
  ) %>% 

  colformat_num(j = "FY", big.mark = "") %>%
  colformat_double(j = c("fid.r.total.audit",
                      "db.original.total.revenue", 
                      # "db.final.total.revenue",
                      "db.orig.rev.error"
                      # "db.final.rev.error"
                      ), 
                big.mark = ",",
                digits = 0) %>%

  flextable_custom_theme()




```






```{r}


FA_Data_District %>% 
  filter(FY > (fiscal.year - prior.years.to.show),
         !is.na(est.1.rev.total.pct.act)) %>% 
  select(FY, db.original.total.expenditure, fid.e.total.xtrans, db.orig.exp.error) %>% 
  flextable() %>% 
  set_header_labels(
                  FY = "Fiscal Year",
                  fid.e.total.xtrans = "Actual Expenditure",
                  db.original.total.expenditure = "District Original Budget Expenditure",
                  # db.final.total.expenditure = "District Final Budget Expenditure",
                  db.orig.exp.error = "Original Budget Error (Budget - Actual)"
                  # db.final.exp.error = "Final Budget Error (Budget - Actual)"
                  
  ) %>% 

  
  colformat_num(j = "FY", big.mark = "") %>%
  colformat_double(j = c("fid.e.total.xtrans",
                      "db.original.total.expenditure", 
                      # "db.final.total.expenditure",
                      "db.orig.exp.error"
                      # "db.final.exp.error"
                      ), 
                big.mark = ",",
                digits = 0) %>%

  flextable_custom_theme()





```
