---
---

## Foundation Allowance


```{r Out of Formula Check}

district_is_out_of_formula <- 
  FA_Data_District %>% 
  filter(FY == max(FY)) %>% 
  select(flag.out.of.formula) %>%
  pull() == "Yes"
  



```


```{r, Per Pupil Foundation Table, eval=(district_is_out_of_formula == FALSE)}

FA_Data_District %>%
  select(FY, cy.d.found.pp, cy.d.found.pp.chg, cy.d.found.pp.pct.chg) %>%
  flextable() %>%
  set_header_labels(FY = "Fiscal Year",
                    cy.d.found.pp = "Foundation Allowance",
                    cy.d.found.pp.chg = "Change",
                    cy.d.found.pp.pct.chg = "Pct Change") %>%
  colformat_num(j = "FY", big.mark = "") %>%
  colformat_num(j = c("cy.d.found.pp", "cy.d.found.pp.chg"), big.mark = ",")%>%
  colformat_double(j = "cy.d.found.pp.pct.chg", suffix = "%") %>% 
  flextable_custom_theme()



```


```{r Per Pupil Foundation Figure, eval=(district_is_out_of_formula == FALSE)}

FA_Data_District %>%
  ggplot(aes(x = FY))+
  geom_line(aes(y = cy.d.found.pp), color = mea_gray, size = line_size)+
  scale_x_continuous(breaks = seq(1990, 2100, by = 1) )+
  scale_y_continuous(labels = number_format(big.mark = ","))+
  labs(title = "Foundation Allowance",
       x = "Fiscal Year",
       y = "")

```

```{r eval=(district_is_out_of_formula == FALSE)}
cat('\\pagebreak')
```





```{r Total Foundation Revenue, eval=(district_is_out_of_formula == FALSE)}

FA_Data_District %>%
  select(FY, cy.d.found.pp, cy.d.pupilcnt, cy.d.found.rev, cy.d.found.rev.chg, cy.d.found.rev.pct.chg) %>%
  flextable() %>%
  set_header_labels(FY = "Fiscal Year",
                    cy.d.found.pp = "Foundation Allowance Per Pupil",
                    cy.d.pupilcnt = "State Aid Membership",
                    cy.d.found.rev = "Total Estimated Foundation Allowance",
                    cy.d.found.rev.chg = "Change", 
                    cy.d.found.rev.pct.chg = "Percent Change") %>%
  colformat_num(j = "FY", big.mark = "") %>%
  colformat_num(j = c("cy.d.found.pp", 
                      "cy.d.pupilcnt", 
                      "cy.d.found.rev", 
                      "cy.d.found.rev.chg"), big.mark = ",") %>% 
  colformat_double(j = "cy.d.found.rev.pct.chg", suffix = "%") %>% 
  flextable_custom_theme() 


```

```{r eval=(district_is_out_of_formula == FALSE)}

FA_Data_District %>%
  ggplot(aes(x = FY))+
  geom_line(aes(y = cy.d.found.rev), color = mea_gray, size = line_size)+
  scale_x_continuous(breaks = seq(1990, 2100, by = 1) )+
  scale_y_continuous(labels = number_format(big.mark = ","))+
  labs(title = "Total Estimated Foundation Allowance Revenue",
       x = "Fiscal Year",
       y = "")



```

`r if(district_is_out_of_formula) {
"This district is out of the foundation allowance formula. Consequently, the district's foundation allowance is determined strictly by the its non-homestead (NHS) taxable value (TV) and their millage rate. The table below estimates the total and per pupil foundation allowance. "}`


```{r eval = district_is_out_of_formula }



FA_Data_District %>%
  select(FY, flag.out.of.formula, cy.d.1.pupilcnt, 
         cy.d.1.nhs.basic, cy.d.1.nhs.sev) %>% 
  mutate(est.foundation.amount = (cy.d.1.nhs.sev / 1000) *cy.d.1.nhs.basic,
         est.foundation.amount.pp = round(est.foundation.amount /cy.d.1.pupilcnt, 0)) %>% 
  flextable() %>% 
 set_header_labels(FY = "Fiscal Year",
                  flag.out.of.formula = "Out-of-formula",
                  cy.d.1.pupilcnt = "State Aid Membership",
                  cy.d.1.nhs.sev = "NHS TV",
                  cy.d.1.nhs.basic = "NHS Millage Rate",
                  est.foundation.amount = "Total Estimated Foundation Allowance",
                  est.foundation.amount.pp = "Total Estimated Foundation Allowance Per Pupil") %>% 
  colformat_num(j = "FY", big.mark = "") %>%
  colformat_num(j = c("cy.d.1.pupilcnt", "cy.d.1.nhs.sev", 
                      "est.foundation.amount", "est.foundation.amount.pp" ), 
                big.mark = ",", digits = 0)%>%
  colformat_double(j = "cy.d.1.nhs.basic", digits = 2) %>% 
  flextable_custom_theme()


  
  
```







