---
output: html_document
---

## Student Transfers

Michigan's school choice laws permit resident students to transfer to a non-resident district or charter school. Conversely, student from outside the district can transfer into the district subject to district policies. Table 18 and figure 9 show the number of students FTE transferring into and out of the district over time. 


```{r}


FA_Data_District %>%
  select(FY, nrs.stu.transfer.in, nrs.stu.transfer.out, nrs.stu.transfer.net) %>% 
  filter(FY != fiscal.year) %>% 
  flextable() %>% 
  set_header_labels(FY = "Fiscal Year",
                    nrs.stu.transfer.in = "Transfers In",
                    nrs.stu.transfer.out = "Transfers Out",
                    nrs.stu.transfer.net = "Net Transfers") %>%
  colformat_double(big.mark = ",", digits = 0) %>% 
  colformat_num(j = "FY", big.mark = "") %>% 
  bg(j = "nrs.stu.transfer.in", bg = mea_green_light, part = "all") %>%
  bg(j = "nrs.stu.transfer.out", bg = mea_red_light, part = "all") %>% 
  bg(j = "nrs.stu.transfer.net", bg = mea_blue_light, part = "all") %>% 

  flextable_custom_theme(title = "Table 18. Student Transfers")


```


```{r}


FA_Data_District %>%
  filter(FY != fiscal.year) %>% 
  select(FY, nrs.stu.transfer.in, nrs.stu.transfer.out, nrs.stu.transfer.net) %>% 
  pivot_longer(cols = c(nrs.stu.transfer.in, nrs.stu.transfer.out, nrs.stu.transfer.net)) %>% 
  mutate(name = case_match(name,
                           "nrs.stu.transfer.in" ~ "Transfer In",
                           "nrs.stu.transfer.out" ~ "Transfer Out",
                           "nrs.stu.transfer.net" ~ "Net Transfer")) %>% 
  ggplot(aes(x = FY, y = value, 
             group = name,  color = name, linetype = name))+
  geom_line(size = line_size) +
  geom_hline(yintercept = 0) +
  scale_x_continuous(breaks = seq(1990, 2100, by = 1) )+
  scale_y_continuous(labels = number_format(big.mark = ","))+
  scale_color_manual(values = c(mea_blue, mea_green, mea_red)) +
  scale_linetype_manual(values=c(1, 6, 3)) +

  labs(title = "Figure 10. Student Transfers",
       x = "Fiscal Year",
       y = "") +
   theme(legend.box.background = element_rect(color= mea_gray, size=1),
        legend.title = element_blank(),
        legend.position = "bottom")





```








