---

---

## Fund Balance

```{r}


FA_Data_District %>%
  ungroup() %>% 
  filter(FY != fiscal.year) %>% 
  select(FY, fid.b.fb11, fid.b.fb11.chg, fid.b.fb11.pct.chg, fid.b.fb.11.pct.rev, fid.b.fb.11.pct.exp) %>%  
  flextable() %>% 
  add_header_lines(values = "General Fund") %>% 

  set_header_labels(FY = "Fiscal Year",
                  fid.b.fb11 = "Amount",
                  fid.b.fb11.chg = "Change",
                  fid.b.fb11.pct.chg = "% Change",
                  fid.b.fb.11.pct.rev = "% of Revenue",
                  fid.b.fb.11.pct.exp = "% of Expenditure") %>% 
  colformat_num(j = "FY",
                big.mark = "") %>%
  colformat_double(j = c("fid.b.fb11", 
                         "fid.b.fb11.chg"), 
                   big.mark = ",",
                   digits = 0) %>%
  colformat_double(j = c("fid.b.fb11.pct.chg", 
                         "fid.b.fb.11.pct.rev", 
                         "fid.b.fb.11.pct.exp"), 
                   suffix = "%") %>% 
  flextable_custom_theme()
 

```


```{r}

# max_fb <- FA_Data_District %>% mutate(x = (fid.b.fb.11.pct.exp / 100)+ .03) %>% pull()

FA_Data_District %>% 
  ggplot(aes(x = FY)) + 
  geom_line(aes(y = fid.b.fb.11.pct.exp / 100), size = line_size, color = mea_gray) +
  # geom_line(aes(y = fid.b.fb11), color = mea_red)+
  geom_hline(yintercept = .05, lty = 2) +
  geom_hline(yintercept = 0) +

  scale_x_continuous(breaks = seq(1990, 2100, by = 1) )+
  scale_y_continuous(labels = percent_format(), 
                     # limits = c(0, max_fb)
                     )+
  labs(title = "General Fund Balance % Expenditure",
       x = "Fiscal Year",
       y = "")

```



\newpage



```{r}

FA_Data_District %>% 
  filter(FY == fiscal.year - 1) %>% 
  ungroup() %>% 
  fa_helper_fa_data_to_transfer_data() %>% 
  ungroup() %>% 
  select(fund.name.trans.to, fund.balance.restricted, fund.balance.unrestricted, fund.balance) %>% 
  flextable() %>% 
  add_header_lines(values = "Fund Balances") %>% 
  set_header_labels(fund.name.trans.to = "Fund",
                    fund.balance.restricted = "Restricted",
                    fund.balance.unrestricted = "Unrestricted",
                    fund.balance = "Total") %>% 
  colformat_double(j = c("fund.balance.restricted", 
                         "fund.balance.unrestricted",
                         "fund.balance"), 
                   big.mark = ",",
                   digits = 0) %>%

  flextable_custom_theme()


```




